### ISSUE TITLE
User (myself) page

### ISSUE THREAD

**Issue by IanButcher** [IanButcher/BitQualy--LAFALDA#56]
A page to see my own data, and have options to edit/update stuff
Should have: 

- Profile picture
- Name
- Last name
- Email
- Password (hidden)
- Button to see password
- Role
- Evaluaciones I got assigned
- Evaluaciones I've done
- Evaluaciones I've assigned

An edit indicator

**Comment by IanButcher** [comment]
#76

**Comment by FabricioColedani** [comment]
Part of Frontend Finalized with all the requested requirements
